// this function checks if city is in large population density list and adjusts radius accordingly to prevent too much data from being retrieved from server

const checkIfLargeCity = (currentCity, region) => {
    let isLarge = false;

    for (const city of largeCities) {
        if (city.city === currentCity && city.state === region) {
            isLarge = true;
            break;
        }
    }
    if (isLarge) {
        return 0.25
    }
    return 0.5
}
export default checkIfLargeCity;

// top 100 largest cities in US
const largeCities = [
    { city: 'New York', state: 'NY', popDensity: '301.5' },
    { city: 'Providence', state: 'RI', popDensity: 'Unknown' },
    { city: 'Los Angeles', state: 'CA', popDensity: ' 468.7' },
    { city: 'Chicago', state: 'IL', popDensity: '227.3' },
    { city: 'Houston', state: 'TX', popDensity: '637.5' },
    { city: 'Phoenix', state: 'AZ', popDensity: '517.6' },
    { city: 'Philadelphia', state: 'PA', popDensity: '134.2' },
    { city: 'San Antonio', state: 'TX', popDensity: '461.0' },
    { city: 'San Diego', state: 'CA', popDensity: '325.2' },
    { city: 'Dallas', state: 'TX', popDensity: '340.9' },
    { city: 'San Jose', state: 'CA', popDensity: '177.5' },
    { city: 'Austin', state: 'TX', popDensity: '312.7' },
    { city: 'Jacksonville', state: 'FL', popDensity: '747.4' },
    { city: 'Fort Worth', state: 'TX', popDensity: '342.9' },
    { city: 'Columbus', state: 'OH', popDensity: '218.5' },
    { city: 'Charlotte', state: 'NC', popDensity: '305.4' },
    { city: 'San Francisco', state: 'CA', popDensity: '46.9' },
    { city: 'Indianapolis', state: 'IN', popDensity: '361.5' },
    { city: 'Seattle', state: 'WA', popDensity: '83.8' },
    { city: 'Denver', state: 'CO', popDensity: '153.3' },
    { city: 'Washington', state: 'D.C.', popDensity: '61.1' },
    { city: 'Boston', state: 'MA', popDensity: '48.3' },
    { city: 'El Paso', state: 'TX', popDensity: '256.8' },
    { city: 'Nashville', state: 'TN', popDensity: '475.9' },
    { city: 'Detroit', state: 'MI', popDensity: '138.8' },
    { city: 'Oklahoma City', state: 'OK', popDensity: '606.3' },
    { city: 'Portland', state: 'OR', popDensity: '133.5' },
    { city: 'Las Vegas', state: 'NV', popDensity: '134.4' },
    { city: 'Memphis', state: 'TN', popDensity: '317.4' },
    { city: 'Louisville', state: 'KY', popDensity: '263.5' },
    { city: 'Baltimore', state: 'MD', popDensity: '80.9' },
    { city: 'Milwaukee', state: 'WI', popDensity: '96.2' },
    { city: 'Albuquerque', state: 'NM', popDensity: '188.2' },
    { city: 'Tucson', state: 'AZ', popDensity: '230.8' },
    { city: 'Fresno', state: 'CA', popDensity: '114.4' },
    { city: 'Mesa', state: 'AZ', popDensity: '137.9' },
    { city: 'Sacramento', state: 'CA', popDensity: '97.9' },
    { city: 'Atlanta', state: 'GA', popDensity: '133.5' },
    { city: 'Kansas City', state: 'MO', popDensity: '315.0' },
    { city: 'Colorado Springs', state: 'CO', popDensity: '195.6' },
    { city: 'Omaha', state: 'NE', popDensity: '133.2' },
    { city: 'Raleigh', state: 'NC', popDensity: '145.1' },
    { city: 'Miami', state: 'FL', popDensity: '36.0' },
    { city: 'Long Beach', state: 'CA', popDensity: '50.3' },
    { city: 'Virginia Beach', state: 'VA', popDensity: '244.7' },
    { city: 'Oakland', state: 'CA', popDensity: '55.9' },
    { city: 'Minneapolis', state: 'MI', popDensity: '54.0' },
    { city: 'Tulsa', state: 'OK', popDensity: '196.8' },
    { city: 'Tampa', state: 'FL', popDensity: '113.4' },
    { city: 'Arlington', state: 'TX', popDensity: '95.8' },
    { city: 'New Orleans', state: 'LA', popDensity: '169.4' },
    { city: 'Wichita', state: 'KS', popDensity: '160.4' },
    { city: 'Bakersfield', state: 'CA', popDensity: '148.8' },
    { city: 'Cleveland', state: 'OH', popDensity: '77.7' },
    { city: 'Aurora', state: 'CO', popDensity: '153.5' },
    { city: 'Anaheim', state: 'CA', popDensity: '+4.19%' },
    { city: 'Honolulu', state: 'HI', popDensity: '60.5' },
    { city: 'Santa Ana', state: 'CA', popDensity: '27.1' },
    { city: 'Riverside', state: 'CA', popDensity: '81.2' },
    { city: 'Corpus Christi', state: 'TX', popDensity: '174.6' },
    { city: 'Lexington', state: 'KY', popDensity: '283.6' },
    { city: 'Henderson', state: 'NV', popDensity: '104.7' },
    { city: 'Stockton', state: 'CA', popDensity: '61.7' },
    { city: 'Saint Paul', state: 'MN', popDensity: '52.0' },
    { city: 'Cincinnati', state: 'OH', popDensity: '77.4' },
    { city: 'St. Louis', state: 'MO', popDensity: '62.0' },
    { city: 'Pittsburgh', state: 'PA', popDensity: '55.4' },
    { city: 'Greensboro', state: 'NC', popDensity: '128.3' },
    { city: 'Lincoln', state: 'NE', popDensity: '92.1' },
    { city: 'Anchorage', state: 'AK', popDensity: '1,706.6' },
    { city: 'Plano', state: 'TX', popDensity: '71.7' },
    { city: 'Orlando', state: 'FL', popDensity: '105.2' },
    { city: 'Irvine', state: 'CA', popDensity: '65.6' },
    { city: 'Newark', state: 'NJ', popDensity: '24.1' },
    { city: 'Durham', state: 'NC', popDensity: '109.8' },
    { city: 'Chula Vista', state: 'CA', popDensity: '49.6' },
    { city: 'Toledo', state: 'OH', popDensity: '80.7' },
    { city: 'Fort Wayne', state: 'IN', popDensity: '110.6' },
    { city: 'St. Petersburg', state: 'FL', popDensity: '61.8' },
    { city: 'Laredo', state: 'TX', popDensity: '101.1' },
    { city: 'Jersey City', state: 'NJ', popDensity: '14.8' },
    { city: 'Chandler', state: 'AZ', popDensity: '64.9' },
    { city: 'Madison', state: 'WI', popDensity: '77.0' },
    { city: 'Lubbock', state: 'TX', popDensity: '124.6' },
    { city: 'Scottsdale', state: 'AZ', popDensity: '183.9' },
    { city: 'Reno', state: 'NV', popDensity: '107.3' },
    { city: 'Buffalo', state: 'NY', popDensity: '40.4' },
    { city: 'Gilbert', state: 'AZ', popDensity: '68.0' },
    { city: 'Glendale', state: 'AZ', popDensity: '59.1' },
    { city: 'North Las Vegas', state: 'NV', popDensity: '98.0' },
    { city: 'Winston–Salem', state: 'NC', popDensity: '132.5' },
    { city: 'Chesapeake', state: 'VA', popDensity: '338.5' },
    { city: 'Norfolk', state: 'VA', popDensity: '53.3' },
    { city: 'Fremont', state: 'CA', popDensity: '77.5' },
    { city: 'Garland', state: 'TX', popDensity: '+5.75%' },
    { city: 'Irving', state: 'TX', popDensity: '67.0' },
    { city: 'Hialeah', state: 'FL', popDensity: '21.5' },
    { city: 'Richmond', state: 'VA', popDensity: '59.8' },
    { city: 'Boise', state: 'ID', popDensity: '82.1' },
    { city: 'Spokane', state: 'WA', popDensity: '68.7' },
    { city: 'Baton Rouge', state: 'LA', popDensity: '85.9' }
]